### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by laojianzi** [laojianzi/kql-go#1]
Our goal is to parse the KQL query to get AST, and then use AST to achieve some goals, e.g.: converting it into an SQL query

- Parser
  - [ ] only value `value` `"value"`
  - [ ] field and value `field: value` `field: "value"`
  - [ ] value wildcards `*` `valu*` `50*`
  - [ ] keyword `OR` `AND` `NOT`
  - [ ] operator `:` `>` `<` `>=` `<=`
  - [ ] subquery `(field: value AND number > 10)` `field: (v1 OR v2)`
  - [ ] escape `field: https\://example.com`
  - [ ] nested fields `user.names.first` and `user.names:{ first: "Alice" and last: "White" }`
  - [ ] field wildcards `fields.*: value`
  - [ ] [date math](https://www.elastic.co/guide/en/elasticsearch/reference/8.15/common-options.html#date-math)
- Apps & Libs
  - [ ] ClickHouse SQL
  - [ ] PRSQL
